# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gibbs_e_it_ann <- function(beta_mat, G_mat, n_SNP, n_GibbsStep, true_Gamma, A_mat) {
    .Call('_GGPA2_Gibbs_e_it_ann', PACKAGE = 'GGPA2', beta_mat, G_mat, n_SNP, n_GibbsStep, true_Gamma, A_mat)
}

Gibbs_e_it_no_ann <- function(beta_mat, G_mat, n_SNP, n_GibbsStep) {
    .Call('_GGPA2_Gibbs_e_it_no_ann', PACKAGE = 'GGPA2', beta_mat, G_mat, n_SNP, n_GibbsStep)
}

